version: '3'

services:
  wp:
    networks: 
      - woocommerce
    image: wordpress:latest # https://hub.docker.com/_/wordpress/
    ports:
      - 80:80 # change ip if required
    volumes:
      - ./config/php.conf.uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./wp-app:/var/www/html
      #- ./plugin-name/trunk/:/var/www/html/wp-content/plugins/plugin-name # For plugin development
      #- ./theme-name/trunk/:/var/www/html/wp-content/themes/theme-name # For theme development
    environment:
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: password
    depends_on:
      - db

  wpcli:
    networks: 
      - woocommerce
    image: wordpress:cli
    user: xfs
    volumes:
      - ./wp-app:/var/www/html
    depends_on:
      - db
      - wp

  phpmyadmin:
    networks: 
      - woocommerce
    image: phpmyadmin/phpmyadmin
    ports:
      - 8091:80
    environment:
      MYSQL_ROOT_PASSWORD: password
    depends_on:
      - db
        
  db:
    networks: 
      - woocommerce
    image: mysql:latest # https://hub.docker.com/_/mysql/ - or mariadb https://hub.docker.com/_/mariadb
    # ports:
    #  - 3306:3306 # change ip if required
    command: [
        '--default_authentication_plugin=mysql_native_password',
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci'
    ]
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_ROOT_PASSWORD: password

volumes:
  db_data:
networks: 
  woocommerce:
    driver: overlay
